name: MySQL Backup to R2

on:
  schedule:
    - cron: "0 23 * * *"   # каждый день в 03:00 по Баку (UTC+4 → 23:00 UTC)
  workflow_dispatch:       # запуск вручную из вкладки Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL Client & AWS CLI2
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client awscli gzip

      - name: Check AWS CLI
        run: aws --version

      - name: Dump MySQL and Upload to R2
        run: |
          FILENAME="db_backup_$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"
          echo ">>> Dumping database to $FILENAME"
          mysqldump -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} ${{ secrets.DB_NAME }} \
            | gzip > $FILENAME
          
          echo ">>> Uploading to Cloudflare R2..."
          aws s3 cp $FILENAME s3://${{ secrets.S3_BUCKET }}/$FILENAME \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
