name: MySQL Backup to R2

on:
  schedule:
    - cron: "0 23 * * *"   # каждый день в 03:00 по Баку
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client curl unzip gzip

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Dump MySQL and Upload to R2
        run: |
          FILENAME="db_backup_$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"
          echo ">>> Dumping database to $FILENAME"
          mysqldump -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} ${{ secrets.DB_NAME }} \
            | gzip > $FILENAME
          
          echo ">>> Uploading to Cloudflare R2..."
          aws s3 cp $FILENAME s3://${{ secrets.S3_BUCKET }}/$FILENAME \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
