name: MySQL Backup to R2

on:
  schedule:
    - cron: "0 1 * * *"   # запуск каждый день в 01:00 UTC (05:00 по Баку)
  workflow_dispatch:       # возможность запускать вручную

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y default-mysql-client gzip unzip curl

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Dump MySQL and Upload to R2
        run: |
          FILENAME="db_backup_$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"
          mysqldump -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} ${{ secrets.DB_NAME }} \
            | gzip > $FILENAME
          aws s3 cp $FILENAME s3://${{ secrets.S3_BUCKET }}/$FILENAME \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
