name: MySQL Backup to Cloudflare R2

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:       # запуск вручную из вкладки Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client unzip curl

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: Debug ENV (проверка что секреты подхватились)
        run: |
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_USER=$DB_USER"
          echo "DB_NAME=$DB_NAME"
          echo "R2_ACCOUNT_ID=$R2_ACCOUNT_ID"
          echo "S3_BUCKET=$S3_BUCKET"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Test DB connection (show tables)
        run: |
          echo ">>> Checking DB connection..."
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASS $DB_NAME -e "SHOW TABLES;"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Dump MySQL with error logging
        run: |
          FILENAME="db_backup_$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"
          echo ">>> Dumping database to $FILENAME"

          # дамп с логами ошибок
          mysqldump --verbose \
            -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASS $DB_NAME \
            2> dump_error.log | gzip > $FILENAME

          echo ">>> Dump errors (if any):"
          cat dump_error.log || true

          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Upload to Cloudflare R2
        run: |
          echo ">>> Uploading $FILENAME to Cloudflare R2..."
          aws s3 cp $FILENAME s3://$S3_BUCKET/$FILENAME \
            --endpoint-url https://$R2_ACCOUNT_ID.r2.cloudflarestorage.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          FILENAME: ${{ env.FILENAME }}
