- name: Dump MySQL and Upload to R2
  env:
    # Эти переменные окружения aws cli использует автоматически
    AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  run: |
    # Проверка на случай, если секрет все еще пуст
    if [ -z "${{ secrets.R2_ACCOUNT_ID }}" ]; then
      echo "Ошибка: Секрет R2_ACCOUNT_ID не задан!"
      exit 1
    fi

    FILENAME="db_backup_$(date +'%Y-%m-%d_%H-%M-%S').sql.gz"
    echo ">>> Dumping database to $FILENAME"
    mysqldump -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u${{ secrets.DB_USER }} -p"${{ secrets.DB_PASS }}" ${{ secrets.DB_NAME }} \
      | gzip > $FILENAME
    
    echo ">>> Uploading to Cloudflare R2..."
    aws s3 cp $FILENAME s3://${{ secrets.S3_BUCKET }}/$FILENAME \
      --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
